// Supabase Edge Function: gmail-sync
// Required secrets: GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET
// Refresh tokens should be stored server-side in public.gmail_tokens (service-role only).
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const CORS={ 'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type' }
const decode=(s='')=>{try{return atob(s.replace(/-/g,'+').replace(/_/g,'/'))}catch{return''}}
const textOf=(p:any):string=>{if(!p)return'';if(p.body?.data)return decode(p.body.data);for(const x of p.parts||[]){if(x.mimeType==='text/plain'&&x.body?.data)return decode(x.body.data)}for(const x of p.parts||[]){const t=textOf(x);if(t)return t}return''}
function classify(s:string){const q=s.toLowerCase();let club='';if(q.includes('arsenal'))club='arsenal';else if(q.includes('liverpool'))club='liverpool';else if(q.includes('manchester united')||q.includes('man utd'))club='manutd';let type='other';if(q.includes('ballot'))type='ballot';else if(q.includes('refund'))type='refund';else if(q.includes('forward')||q.includes('transfer'))type='transfer';else if(q.includes('membership'))type='membership';else if(q.includes('ticombo')||q.includes('1boxoffice')||q.includes('1 box office')||q.includes('sale confirmation'))type='sale';else if(q.includes('ticket')||q.includes('booking')||q.includes('order confirmation'))type='ticket';const refs=[...s.matchAll(/(?:order|booking|transaction|reference|ref)\s*(?:id|no|number|#)?\s*[:#-]?\s*([A-Z0-9-]{5,})/ig)].map(m=>m[1]);return{club,type,refs:[...new Set(refs)].slice(0,5)}}
async function accessToken(refresh:string){const body=new URLSearchParams({client_id:Deno.env.get('GOOGLE_CLIENT_ID')||'',client_secret:Deno.env.get('GOOGLE_CLIENT_SECRET')||'',refresh_token:refresh,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error('Google token refresh failed');return (await r.json()).access_token}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});try{const auth=req.headers.get('Authorization')||'';const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}});const {data:{user}}=await sb.auth.getUser();if(!user)throw new Error('Not signed in');const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const {data:tok}=await admin.from('gmail_tokens').select('refresh_token').eq('user_id',user.id).maybeSingle();if(!tok?.refresh_token)throw new Error('No Gmail refresh token stored for this user');const token=await accessToken(tok.refresh_token);const q=encodeURIComponent('(Arsenal OR Liverpool OR "Manchester United" OR Ticombo OR "1BoxOffice" OR ticket OR booking OR ballot) newer_than:365d');const lr=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=100&q='+q,{headers:{Authorization:'Bearer '+token}});const list=await lr.json();let added=0;for(const m of list.messages||[]){const mr=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/'+m.id+'?format=full',{headers:{Authorization:'Bearer '+token}});const full=await mr.json();const hs=Object.fromEntries((full.payload?.headers||[]).map((h:any)=>[h.name.toLowerCase(),h.value]));const body=textOf(full.payload),subject=hs.subject||'',sender=hs.from||'',combined=[subject,sender,body].join('\n'),c=classify(combined);const confidence=(c.club?0.35:0)+(c.type!=='other'?0.35:0)+(c.refs.length?0.25:0);const needs=confidence<0.7;const {error}=await admin.from('inbox_events').upsert({user_id:user.id,external_id:m.id,event_type:c.type,club_id:c.club||null,sender,subject,body,event_date:new Date(Number(full.internalDate||Date.now())).toISOString(),confidence,needs_review:needs,review_reason:needs?'Missing club/type/reference confidence':'',extracted:{references:c.refs}},{onConflict:'user_id,external_id',ignoreDuplicates:true});if(!error)added++}return new Response(JSON.stringify({message:`Processed Gmail; ${added} new/checked messages`,added}),{headers:{...CORS,'content-type':'application/json'}})}catch(e){return new Response(JSON.stringify({error:String(e.message||e)}),{status:400,headers:{...CORS,'content-type':'application/json'}})}})
